name: Update Feeds

on:
  schedule:
    - cron: "0 0 */2 * *"
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # setup
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.14        
      - name: checkout
        uses: actions/checkout@v2
      - name: get the feed-cli
        run: go get github.com/nhomble/feed-cli
      
      # create
      - name: create site
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
        run: |
          make clean website

      # update
      - name: update index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update feed
  notify:
    runs-on: ubuntu-latest
    needs: update
    steps:     
      - name: Send GroupMe notification
        uses: nhomble/groupme-notify-action@v1.2
        id: notify
        with:
          bot: ${{ secrets.GROUPME_BOT }}
          message: 'Checkout the new feeds at: https://nhomble.github.io/fdmi/'
          token: ${{ secrets.GO_GROUPME_API_TOKEN }}
