name: Update Feeds

on:
  schedule:
    - cron: "30 2 * * *"
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # setup
      - name: checkout
        uses: actions/checkout@v2
      - name: get the feed-cli
        run: go get github.com/nhomble/feed-cli
      
      # create
      - name: create index
        run: |
          cat feeds | go run github.com/nhomble/feed-cli > index.html

      # update
      - name: update index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update feed
