name: Update Feeds

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # setup
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14        
      - name: checkout
        uses: actions/checkout@v2
      - name: get the feed-cli
        run: go get github.com/nhomble/feed-cli
      - name: checkout release
        run: |
          cd $GOPATH/src/github.com/nhomble/feed-cli && git checkout v0.1.0 && cd -
      
      # create
      - name: create index
        run: |
          cat feeds | go run github.com/nhomble/feed-cli -templateOverride index.tpl > index.html        

      # update
      - name: update index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update feed
