name: Update Feeds

on:
  schedule:
    - cron: "*/1 * * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@master
        
      - name: create feed input
        run: |
          touch feeds
          echo "http://rss.cnn.com/rss/cnn_topstories.rss" >> feeds
      - name: create index
        run: |
          pwd
          ls feed-cli/
          cat $feeds | go run feed-cli/feed.go > index.html
      - name: update index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update feed
