name: Update Feeds

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # setup
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14        
      - name: checkout
        uses: actions/checkout@v2
      - name: get the feed-cli
        run: go get github.com/nhomble/feed-cli
      
      # create
      - name: create index
        run: |
          cat feeds | go run github.com/nhomble/feed-cli -templateOverride index.tpl > index.html        

      # update
      - name: update index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update feed
  notify:
    runs-on: ubuntu-latest
    needs: update
    steps:     
      - name: Send GroupMe notification
        uses: nhomble/groupme-notify-action@v0.3
        id: notify
        with:
          group: ${{ secrets.GROUPME_GROUP }}
          message: 'Checkout the new feeds: https://nhomble.github.io/fdmi/'
          token: ${{ secrets.GO_GROUPME_API_TOKEN }}
